name: Corretor da lista de exercícios da Python Brasil

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configuração de Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Correção do Exercício 01 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_01_alo_mundo.py
    - name: Correção do Exercício 02 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_02_escreva_um_numero.py
    - name: Correção do Exercício 03 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_03_imprima_soma_de_dois_numeros.py
    - name: Correção do Exercício 04 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_04_notas_bimestrais.py
    - name: Correção do Exercício 05 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_05_metros_para_centimetros.py
    - name: Correção do Exercício 06 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_06_area_circulo.py
    - name: Correção do Exercício 07 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_07_area_quadrado.py
    - name: Correção do Exercício 08 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_08_horas_trabalhadas_mes.py
    - name: Correção do Exercício 09 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_09_fahrenheit_para_celsius.py
    - name: Correção do Exercício 10 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_10_celsius_para_fahrenheit.py
    - name: Correção do Exercício 11 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_11_contas_matematicas.py
    - name: Correção do Exercício 12 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_12_peso_ideal.py
    - name: Correção do Exercício 13 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_13_peso_ideal_mulher_e_homem.py
    - name: Correção do Exercício 14 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_14_joao_papo_de_pescador.py
    - name: Correção do Exercício 15 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_15_clt_onerosa.py
    - name: Correção do Exercício 16 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_16_loja_de_tintas_simples.py
    - name: Correção do Exercício 17 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_17_loja_de_tintas_complexa.py
    - name: Correção do Exercício 18 da seção de Estrutura Sequencial
      if: always()
      run: |
        python -m doctest -f secao_01_estrutura_sequencial/ex_18_tempo_de_download.py
    - name: Correção do Exercício 01 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_01_imprimir_maior_numero.py
    - name: Correção do Exercício 02 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_02_positivo_ou_negativo.py
    - name: Correção do Exercício 03 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_03_F_ou_M.py
    - name: Correção do Exercício 04 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_04_vogal_ou_consoante.py
    - name: Correção do Exercício 05 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_05_notas_parciais.py
    - name: Correção do Exercício 06 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_06_maior_numero_de_3_numeros.py
    - name: Correção do Exercício 07 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_07_maior_e_menor_numero_de_3_numeros.py
    - name: Correção do Exercício 08 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_08_escolha_de_produto.py
    - name: Correção do Exercício 09 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_09_numeros_decrescentes.py
    - name: Correção do Exercício 10 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_10_cumprimento_em_turno.py
    - name: Correção do Exercício 11 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_11_salario_tabajara.py
    - name: Correção do Exercício 12 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_12_clt_assalto.py
    - name: Correção do Exercício 13 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_13_dia_da_semana.py
    - name: Correção do Exercício 14 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_14_atribuicoes_de_conceitos.py
    - name: Correção do Exercício 15 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_15_triangulo.py
    - name: Correção do Exercício 16 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_16_equacao_segundo_grau.py
    - name: Correção do Exercício 17 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_17_ano_bissexto.py
    - name: Correção do Exercício 18 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_18_validador_de_data.py
    - name: Correção do Exercício 19 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_19_decomposicao_de_numero.py
    - name: Correção do Exercício 20 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_20_3_notas_parciais.py
    - name: Correção do Exercício 21 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_21_troco.py
    - name: Correção do Exercício 22 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_22_par_ou_impar.py
    - name: Correção do Exercício 23 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_23_inteiro_ou_decimal.py
    - name: Correção do Exercício 24 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_24_operacao.py
    - name: Correção do Exercício 25 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_25_sherlock.py
    - name: Correção do Exercício 26 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_26_posto_de_gasolina.py
    - name: Correção do Exercício 27 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_27_hortifruti.py
    - name: Correção do Exercício 28 da seção de Estrutura de Decisão
      if: always()
      run: |
        python -m doctest -f secao_02_estrutura_de_decisao/ex_28_mercado_tabajara.py
    - name: Correção do Exercício 01 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_01_numero_valido.py
    - name: Correção do Exercício 02 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_02_validador_de_senha.py
    - name: Correção do Exercício 03 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_03_validador_de_cadastro.py
    - name: Correção do Exercício 04 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_04_crescimento_populacional.py
    - name: Correção do Exercício 05 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_05_crescimento_populacional_parametrizavel.py
    - name: Correção do Exercício 06 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_06_numeros_1_a_20.py
    - name: Correção do Exercício 07 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_07_maior_de_5_numeros.py
    - name: Correção do Exercício 08 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_08_soma_e_media_de_5_numeros.py
    - name: Correção do Exercício 09 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_09_numeros_impares_de_1_a_50.py
    - name: Correção do Exercício 10 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_10_gerar_numeros_de_intervalo.py
    - name: Correção do Exercício 11 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_11_gerar_numeros_de_intervalo_e_somar.py
    - name: Correção do Exercício 12 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_12_tabuada.py
    - name: Correção do Exercício 13 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_13_potenciacao.py
    - name: Correção do Exercício 14 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_14_qtde_pares_e_impares.py
    - name: Correção do Exercício 15 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_15_fibonnacci_ate_n.py
    - name: Correção do Exercício 16 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_16_fibonnacci_ate_valor_maior_que_500.py
    - name: Correção do Exercício 17 da seção de Estrutura de Repetição
      if: always()
      run: |
        python -m doctest -f secao_03_estrutura_de_repeticao/ex_17_fatorial.py
    - name: Correção do Exercício 18 da seção de Estrutura de Repetição
      if: always()
      run: |
          python -m doctest -f secao_03_estrutura_de_repeticao/ex_18_estatisticas_de_n_numeros.py
    - name: Correção do Exercício 19 da seção de Estrutura de Repetição
      if: always()
      run: |
          python -m doctest -f secao_03_estrutura_de_repeticao/ex_19_estatisticas_de_n_numeros_com_limitacao.py
    - name: Correção do Exercício 20 da seção de Estrutura de Repetição
      if: always()
      run: |
          python -m doctest -f secao_03_estrutura_de_repeticao/ex_20_fatorial_com_limitacao.py
    - name: Correção do Exercício 21 da seção de Estrutura de Repetição
      if: always()
      run: |
          python -m doctest -f secao_03_estrutura_de_repeticao/ex_21_numero_primo.py
    - name: Correção do Exercício 22 da seção de Estrutura de Repetição
      if: always()
      run: |
          python -m doctest -f secao_03_estrutura_de_repeticao/ex_22_numero_primo_divisores.py
    - name: Correção do Exercício 23 da seção de Estrutura de Repetição
      if: always()
      run: |
          python -m doctest -f secao_03_estrutura_de_repeticao/ex_23_primos_menores_que_um_numero.py
    - name: Correção do Exercício 24 da seção de Estrutura de Repetição
      if: always()
      run: |
          python -m doctest -f secao_03_estrutura_de_repeticao/ex_24_media_artmetica.py
    - name: Correção do Exercício 25 da seção de Estrutura de Repetição
      if: always()
      run: |
          python -m doctest -f secao_03_estrutura_de_repeticao/ex_25_classificador_de_turma.py
