name: Corretor da seção de listas da lista de exercícios da Python Brasil

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configuração de Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Correção do Exercício 01 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_01_vetor_5_numeros.py
      - name: Correção do Exercício 02 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_02_vetores_inverso.py
      - name: Correção do Exercício 03 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_03_media_4_notas.py
      - name: Correção do Exercício 05 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_05_vetore_par_e_impar.py
      - name: Correção do Exercício 09 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_06_calculador_de_media.py
      - name: Correção do Exercício 06 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_09_soma_de_quadrados.py
      - name: Correção do Exercício 10 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_10_intercalacao_de_vetores.py
      - name: Correção do Exercício 11 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_11_intercalacao_de_3_vetores.py
      - name: Correção do Exercício 12 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_12_filtro_de_baixinhos.py
      - name: Correção do Exercício 13 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_13_media_de_temperaturas_anual.py
      - name: Correção do Exercício 14 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_24_lancamento_de_dados.py
      - name: Correção do Exercício 18 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_18_melhor_jogador.py
      - name: Correção do Exercício 24 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_14_investigacao.py
